import { Theme } from "../theme_cont/theme.slint";

export component IslandContainer inherits Rectangle {
    in property <int> container-id;
    in property <string> container-name;

    background: Theme.color0;

    border-color: Theme.foreground.with-alpha(0.2);
    border-radius: 8px;
    border-width: 0px;

    layout := HorizontalLayout {
        alignment: center;

        padding-left: 20px;
        padding-right: 20px;

        spacing: 20px;

        @children
    }

    width: layout.preferred-width + 22px;
    height: 36px;
}
