import { ContainerConfig } from "./models.slint";

export global ClockState {
    in-out property <int> hour: 0;
    in-out property <int> minute: 0;
    in-out property <int> seconds: 0;
}

export global DateState {
    in-out property <int> day: 0;
    in-out property <int> month: 0;
    in-out property <int> year: 0;
    in-out property <int> weekday: 0;
}

export global ContainerState {
    in-out property <[ContainerConfig]> containers: [];
}
