import { Theme } from "../../theme_cont/theme.slint";
import "../../../res/fonts/ttyclock.ttf";
import "../../../res/fonts/Blocko.ttf";
import "../../../res/fonts/pixel_maz.ttf";
import "../../../res/fonts/pixeleris.ttf";
import "../../../res/fonts/FFFFORWA.ttf";

export { Theme }

export component Clock inherits HorizontalLayout {
    in property <int> hour;
    in property <int> minute;
    in property <int> seconds;
    in property <bool> show-seconds: true;
    in property <bool> is-24-hour: true;
    in property <bool> show-am-pm: true;

    spacing: 3px;

    pure function format-hour() -> int {
        if (is-24-hour) {
            return hour;
        }

        let h = Math.mod(hour, 12);
        return h == 0 ? 12 : h;
    }

    pure function suffix() -> string {
        if (!show-am-pm || is-24-hour) {
            return "";
        }

        return hour < 12 ? "Am" : "Pm";
    }

    ///////////////////////////////////////-Clock Num-///////////////////////////////////////
    Text {
        text: "\{root.format-hour()}:\{root.minute < 10 ? "0" : ""}\{root.minute}\{root.show-seconds ? ":" + (root.seconds < 10 ? "0" : "") + root.seconds : ""}";
        color: Theme.color12;
        font-family: "ttyclock";
        font-size: 13px;

        vertical-alignment: center;
    }

    ///////////////////////////////////////-Clock Am?Pm-/////////////////////////////////////
    Text {
        text: root.suffix();
        color: Theme.color12;
        font-family: "FFF Forward";
        font-size: 10px;

        vertical-alignment: center;
        y: 3px;

        visible: root.show-am-pm && !root.is-24-hour;
    }
}
