export global Theme {
    in-out property <bool> _dirty: false;

    in-out property <brush> background: #19120f;
    in-out property <brush> foreground: #cbccbe;

    in-out property <brush> color0: #19120f;
    in-out property <brush> color1: #7E8979;
    in-out property <brush> color2: #978B6A;
    in-out property <brush> color3: #CAAF73;
    in-out property <brush> color4: #8E998B;
    in-out property <brush> color5: #A59F8A;
    in-out property <brush> color6: #98A390;
    in-out property <brush> color7: #cbccbe;
    in-out property <brush> color8: #8e8e85;
    in-out property <brush> color9: #7E8979;
    in-out property <brush> color10: #978B6A;
    in-out property <brush> color11: #CAAF73;
    in-out property <brush> color12: #8E998B;
    in-out property <brush> color13: #A59F8A;
    in-out property <brush> color14: #98A390;
    in-out property <brush> color15: #cbccbe;
}
