import { IslandContainer } from "./components/IslandContainer.slint";
import { Theme } from "./theme_cont/theme.slint";

export { Theme }

export component Trigger inherits Window {
    background: transparent;

    out property <bool> hovered: area.has-hover;

    area := TouchArea {
        width: parent.width;
        height: parent.height;
    }
}

export component Island inherits Window {
    background: transparent;

    in property <bool> visible-requested: false;
    ///////////////-Clock-///////////////
    in property <int> current-hour;
    in property <int> current-minute;
    in property <bool> is-24-hour: false;
    in property <bool> show-am-pm: true;
    /////////////////////////////////////
    out property <bool> hovered: area.has-hover;

    out property <length> content-width: island-container.width;
    out property <length> content-height: island-container.height + 2px;

    area := TouchArea {
        width: parent.width;
        height: parent.height;

        island-container := IslandContainer {
            current-hour: root.current-hour;
            current-minute: root.current-minute;
            is-24-hour: root.is-24-hour;
            show-am-pm: root.show-am-pm;

            x: (parent.width - self.width) / 2;
            y: root.visible-requested ? 2px : -self.height;

            opacity: root.visible-requested ? 1 : 0;

            animate y {
                duration: 220ms;
                easing: ease-out;
            }

            animate opacity {
                duration: 180ms;
            }
        }
    }
}
