import { IslandContainer } from "./components/IslandContainer.slint";
import { Clock } from "./components/widgets/clock.slint";
import { Date } from "./components/widgets/date.slint";
import { ClockState, DateState } from "./components/state.slint";
import { Theme } from "./theme_cont/theme.slint";

export { Theme, ClockState, DateState }

export component Trigger inherits Window {
    background: transparent;

    out property <bool> hovered: area.has-hover;

    area := TouchArea {
        width: parent.width;
        height: parent.height;
    }
}

export component Island inherits Window {
    background: transparent;

    in property <bool> visible-requested: false;

    out property <bool> hovered: area.has-hover;

    out property <length> content-width: island-container.width;
    out property <length> content-height: island-container.height + 2px;

    area := TouchArea {
        width: parent.width;
        height: parent.height;

        island-container := IslandContainer {
            container-id: 1;
            container-name: "Main Container";

            Clock {
            show-seconds: false;
            is-24-hour: false;
            show-am-pm: true;
            }
            Date {}

            x: (parent.width - self.width) / 2;
            y: root.visible-requested ? 2px : -self.height;

            opacity: root.visible-requested ? 1 : 0;

            animate y {
                duration: 220ms;
                easing: ease-out;
            }

            animate opacity {
                duration: 180ms;
            }
        }
    }
}
