export global Theme {
    in-out property <color> background;
    in-out property <color> foreground;

    in-out property <color> color0;
    in-out property <color> color1;
    in-out property <color> color2;
    in-out property <color> color3;
    in-out property <color> color4;
    in-out property <color> color5;
    in-out property <color> color6;
    in-out property <color> color7;
    in-out property <color> color8;
    in-out property <color> color9;
    in-out property <color> color10;
    in-out property <color> color11;
    in-out property <color> color12;
    in-out property <color> color13;
    in-out property <color> color14;
    in-out property <color> color15;
}
